name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Hey there! 👋

          Welcome to our repository! We're thrilled to see your interest in contributing.

          If you're opening an issue, please provide as much detail as possible about the problem or feature request you have. This helps us understand your needs better and address them effectively.

          Feel free to reach out if you have any questions or need assistance. Happy coding! 🚀

        pr-message: |
          Hey there! 👋

          Welcome to our repository! We're thrilled to see your interest in contributing.

          If you're opening a pull request, thank you for your contribution! Make sure to include a clear description of the changes you've made and any relevant context.

          Feel free to reach out if you have any questions or need assistance. Happy coding! 🚀